"""revert

Revision ID: 53b1a8f6f14e
Revises: a9b79b0ad050
Create Date: 2024-11-09 14:22:36.021420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53b1a8f6f14e'
down_revision = 'a9b79b0ad050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('city_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('city_code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
