"""Add city_code to UserAddress

Revision ID: a90e7c08c0e1
Revises: ce6a16e82307
Create Date: 2024-11-08 16:08:05.529248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a90e7c08c0e1'
down_revision = 'ce6a16e82307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_code', sa.String(length=10), nullable=False))
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('state')
        batch_op.drop_column('country')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('country', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', mysql.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('city_code')

    # ### end Alembic commands ###
