"""Add address fields to User table

Revision ID: a9b79b0ad050
Revises: cdc4702ad832
Create Date: 2024-11-09 13:54:41.044064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b79b0ad050'
down_revision = 'cdc4702ad832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('street')
        batch_op.drop_column('city_code')

    # ### end Alembic commands ###
