"""Add weight column to items rev 

Revision ID: c458f2fe6055
Revises: 53b1a8f6f14e
Create Date: 2024-11-09 15:03:01.424593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c458f2fe6055'
down_revision = '53b1a8f6f14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
