"""Create UserAddress table with city_code

Revision ID: cdc4702ad832
Revises: a90e7c08c0e1
Create Date: 2024-11-09 13:43:44.886933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cdc4702ad832'
down_revision = 'a90e7c08c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('street')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('postal_code', mysql.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
